### ISSUE TITLE
Moncash broken link in PRODUCTION_ENDPOINTS

### ISSUE THREAD

**Issue by ninjaroot-509** [Lemayzeur/moncashify_sdk#1]
#in constants.py

change ==> REST_API_PRODUCTION_ENDPOINT = 'https://api.moncashbutton.digicelgroup.com'
to =====>   REST_API_PRODUCTION_ENDPOINT = 'https://moncashbutton.digicelgroup.com/Api'

**Comment by Lemayzeur** [comment]
Actually, this is a broken link and needs to be fixed soon! Thank you @ninjaroot-509

**Comment by ninjaroot-509** [comment]
yes brother
