### ISSUE TITLE
Wrong link for REST_API_PRODUCTION_ENDPOINT

### ISSUE THREAD

**Issue by Lemayzeur** [Lemayzeur/moncashify_sdk#2]
REST_API_PRODUCTION_ENDPOINT = 'https://moncashbutton.digicelgroup.com'

This link is not working in production.

**Comment by Lemayzeur** [comment]
The correct link is: `REST_API_PRODUCTION_ENDPOINT = 'https://moncashbutton.digicelgroup.com/Api'`

**Comment by CodonsEnsemble** [comment]
![token issue](https://user-images.githubusercontent.com/52325610/167146758-ad293258-6ef2-4cf2-b660-21394682b780.PNG)
 Please can someone help me , I have a token issue ?

**Comment by Lemayzeur** [comment]
Make sure that you have valid tokens from Moncash. 

Please note also, that the tokens used in development are not the same for the production

**Comment by CodonsEnsemble** [comment]
Hi friend
thank you for response but as you can see I received a token
[image: image.png]

but I don't why it doesn't work



Le ven. 6 mai 2022 à 18:34, Lub Lorry Lamysère ***@***.***> a
écrit :
